/// <reference types="vite-plugin-pwa/client" />

// Service-worker registration helper for the PWA / offline mode.
//
// The actual Workbox service worker is generated by vite-plugin-pwa at build
// time (see vite.config.ts). `virtual:pwa-register` is a build-time virtual
// module the plugin resolves; it does not exist under dev/test, so we import it
// lazily and only when running a PRODUCTION build in a browser that supports
// service workers. jsdom (vitest) and `vite dev` therefore never touch a real
// SW — calling this helper there is a deliberate no-op.

/**
 * Register the generated service worker. No-op unless this is a PROD build
 * running in a browser with service-worker support. Safe to call unconditionally
 * from the app entrypoint; failures are swallowed so a flaky SW never blocks
 * the app from rendering.
 */
export function registerServiceWorker(): void {
  if (!import.meta.env.PROD) return
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return

  // Dynamic import so the virtual module is only pulled in PROD bundles, where
  // the vite-plugin-pwa plugin guarantees it resolves. The specifier is built
  // from a variable (+ `@vite-ignore`) so Vite's static import-analysis does NOT
  // try to resolve `virtual:pwa-register` under vitest — where the PWA plugin is
  // deliberately absent — which would otherwise fail the test suite at transform
  // time even behind the PROD guard. autoUpdate + immediate lets a new build
  // take over on the next load without a user-facing prompt.
  const mod = 'virtual:pwa-register'
  import(/* @vite-ignore */ mod)
    .then((m: typeof import('virtual:pwa-register')) => {
      m.registerSW({ immediate: true })
    })
    .catch(() => {
      // A missing/failed SW must never break the app — offline support is
      // strictly additive.
    })
}
