import { Container, Section, Reveal, Button } from '../ui'

interface Pillar {
  kicker: string
  title: string
  body: string
}

const PILLARS: Pillar[] = [
  {
    kicker: 'Start with you',
    title: 'Interests, not destinations',
    body: 'Tell us what you love — climbing, cooking, quiet museums — and we work outward to the places that fit, instead of handing you the same ten cities everyone gets.',
  },
  {
    kicker: 'Day by day',
    title: 'A plan you can actually follow',
    body: 'Every recommendation becomes a real itinerary: where to be, roughly what it costs, and a map link to get there — not a wall of tabs to reconcile yourself.',
  },
  {
    kicker: 'Honest by default',
    title: 'Grounded and transparent',
    body: 'Suggestions are generated by AI and anchored with cost estimates and sources. We disclose affiliate links and tell you where the data comes from.',
  },
]

interface WhyTAIProps {
  /** Optional id for in-page anchoring (e.g. skip-links). */
  id?: string
  /** Vertical rhythm; matches the host page's band sizing. */
  size?: 'cozy' | 'default' | 'spacious'
  /** Show the closing call-to-action row. Off when the host page has its own. */
  showCta?: boolean
  className?: string
}

/**
 * Reusable "why Travel AI" story band — a kicker, headline, and three pillars,
 * optionally capped with a CTA. Shared by Home and About so the brand story is
 * told once. Built entirely from ui/ primitives; Reveal handles the staggered
 * scroll-in and is reduced-motion safe.
 */
export function WhyTAI({
  id,
  size = 'spacious',
  showCta = true,
  className = '',
}: WhyTAIProps) {
  return (
    <Section id={id} size={size} className={className}>
      <Container>
        <Reveal>
          <div className="max-w-2xl">
            <p className="text-sm font-medium uppercase tracking-[0.18em] text-accent-700">
              Why Travel AI
            </p>
            <h2 className="mt-4 font-serif text-4xl font-medium leading-[1.1] tracking-tight text-ink sm:text-5xl">
              The busywork of planning, carried for you
            </h2>
            <p className="mt-5 text-lg leading-relaxed text-ink-soft">
              The gap between “I’d love to go somewhere” and a bookable plan is
              full of open tabs and guesswork. We close it — beginning with your
              interests and ending with a day-by-day itinerary.
            </p>
          </div>
        </Reveal>

        <div className="mt-12 grid gap-6 sm:mt-16 sm:grid-cols-3">
          {PILLARS.map((pillar, i) => (
            <Reveal key={pillar.title} as="article" index={i}>
              <div className="h-full rounded-2xl border border-ink-line bg-canvas-raised p-7 shadow-frame">
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-ink-faint">
                  {pillar.kicker}
                </p>
                <h3 className="mt-3 font-serif text-xl font-medium leading-snug text-ink">
                  {pillar.title}
                </h3>
                <p className="mt-3 leading-relaxed text-ink-soft">{pillar.body}</p>
              </div>
            </Reveal>
          ))}
        </div>

        {showCta ? (
          <Reveal>
            <div className="mt-12 flex flex-wrap items-center gap-5 sm:mt-16">
              <Button to="/discover" size="lg">
                Plan a trip <span aria-hidden="true">→</span>
              </Button>
              <Button to="/explore" variant="ghost" size="lg">
                Browse destinations
              </Button>
            </div>
          </Reveal>
        ) : null}
      </Container>
    </Section>
  )
}
