// Barrel for shared UI primitives. Pages import from '../components/ui'.
export { Container } from './Container'
export { Section } from './Section'
export { Reveal } from './Reveal'
export { Button } from './Button'
export { MagneticButton } from './MagneticButton'
export { ScrollScale } from './ScrollScale'
export { Confetti } from './Confetti'
export { usePrefersReducedMotion } from './usePrefersReducedMotion'
export { grainOverlayStyle, softGlow, frostedPanel, variableSerif } from './textures'
export { ThemeToggle } from './ThemeToggle'
