import { Link } from 'react-router-dom'
import { Button, Container, Section, Reveal } from '../components/ui'

export default function AboutPage() {
  return (
    <Container>
      <Section>
        <div className="mx-auto max-w-2xl">
          <Reveal>
            <header>
              <p className="text-sm font-medium uppercase tracking-[0.18em] text-accent-700">
                About
              </p>
              <h1 className="mt-4 font-serif text-5xl font-medium leading-[1.08] tracking-tight text-ink sm:text-6xl">
                Planning a trip should feel like the fun part
              </h1>
            </header>
          </Reveal>

          <Reveal>
            <div className="mt-8 space-y-5 text-lg leading-relaxed text-ink-soft">
              <p>
                Travel AI started from a simple frustration: the gap between “I’d love to go
                somewhere” and an actual, bookable plan is full of open tabs, conflicting reviews,
                and guesswork. Most of that work is mechanical — and mechanical work is exactly what
                software should carry for you.
              </p>
              <p>
                So we built a planner that begins with <em>you</em> — your hobbies, your pace, your
                budget — and works outward to destinations and a day-by-day itinerary. The aim isn’t
                to replace the joy of discovery, but to clear away the busywork so the discovery is
                all that’s left.
              </p>
              <p>
                Recommendations are generated by large language models and grounded with cost
                estimates and map links, so every suggestion is something you can act on rather than
                just admire.
              </p>
            </div>
          </Reveal>

          <Reveal>
            <div className="mt-10 rounded-2xl border border-ink-line bg-canvas-raised p-7 shadow-frame">
              <h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-ink-faint">
                What we value
              </h2>
              <ul className="mt-4 space-y-3 leading-relaxed text-ink-soft">
                <li className="flex gap-3">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-500" />
                  <span>
                    <strong className="font-medium text-ink">Made for you.</strong> Plans
                    follow your interests, not a one-size-fits-all template.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-500" />
                  <span>
                    <strong className="font-medium text-ink">Actionable.</strong> Real costs,
                    real map links, real booking options where we have them.
                  </span>
                </li>
                <li className="flex gap-3">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-500" />
                  <span>
                    <strong className="font-medium text-ink">Honest.</strong> We disclose
                    affiliate links and tell you where our data comes from.
                  </span>
                </li>
              </ul>
            </div>
          </Reveal>

          <Reveal>
            <div className="mt-10 flex flex-wrap items-center gap-5">
              <Button to="/discover" size="lg">
                Plan a trip <span aria-hidden="true">→</span>
              </Button>
              <Link
                to="/how-it-works"
                className="text-sm font-medium text-accent-600 underline-offset-4 hover:underline"
              >
                See how it works
              </Link>
            </div>
          </Reveal>
        </div>
      </Section>
    </Container>
  )
}
