import { Link } from 'react-router-dom'
import { Container, Section, Reveal } from '../components/ui'

export default function AboutPage() {
  return (
    <Container>
      <Section>
        <div className="mx-auto max-w-2xl">
          <Reveal>
            <header>
              <p className="text-[11px] font-medium uppercase tracking-[0.22em] text-accent-600">
                About
              </p>
              <h1 className="mt-2 text-4xl font-semibold tracking-tight text-ink">
                Planning a trip should feel like the fun part
              </h1>
            </header>
          </Reveal>

          <Reveal>
            <div className="mt-8 space-y-5 leading-relaxed text-ink-soft">
              <p>
                Travel AI started from a simple frustration: the gap between “I’d love to go
                somewhere” and an actual, bookable plan is full of open tabs, conflicting reviews,
                and guesswork. Most of that work is mechanical — and mechanical work is exactly what
                software should carry for you.
              </p>
              <p>
                So we built a planner that begins with <em>you</em> — your hobbies, your pace, your
                budget — and works outward to destinations and a day-by-day itinerary. The aim isn’t
                to replace the joy of discovery, but to clear away the busywork so the discovery is
                all that’s left.
              </p>
              <p>
                Recommendations are generated by large language models and grounded with cost
                estimates and map links, so every suggestion is something you can act on rather than
                just admire.
              </p>
            </div>
          </Reveal>

          <Reveal>
            <div className="mt-10 rounded-2xl border border-ink-line/80 bg-canvas-raised p-6 shadow-sm">
              <h2 className="text-sm font-semibold uppercase tracking-[0.12em] text-ink-faint">
                What we value
              </h2>
              <ul className="mt-3 space-y-2.5 text-sm leading-relaxed text-ink-soft">
                <li className="flex gap-2.5">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-400" />
                  <span>
                    <strong className="font-medium text-ink">Made for you.</strong> Plans
                    follow your interests, not a one-size-fits-all template.
                  </span>
                </li>
                <li className="flex gap-2.5">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-400" />
                  <span>
                    <strong className="font-medium text-ink">Actionable.</strong> Real costs,
                    real map links, real booking options where we have them.
                  </span>
                </li>
                <li className="flex gap-2.5">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-400" />
                  <span>
                    <strong className="font-medium text-ink">Honest.</strong> We disclose
                    affiliate links and tell you where our data comes from.
                  </span>
                </li>
              </ul>
            </div>
          </Reveal>

          <Reveal>
            <div className="mt-10 flex flex-wrap items-center gap-3">
              <Link
                to="/discover"
                className="inline-flex items-center gap-2 rounded-full bg-accent-600 px-6 py-2.5 text-sm font-semibold text-canvas-raised shadow-sm transition hover:bg-accent-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-500 focus-visible:ring-offset-2"
              >
                Plan a trip
                <span aria-hidden="true">→</span>
              </Link>
              <Link
                to="/how-it-works"
                className="text-sm font-medium text-accent-600 underline-offset-2 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent-500"
              >
                See how it works
              </Link>
            </div>
          </Reveal>
        </div>
      </Section>
    </Container>
  )
}
